---

- src: https://github.com/Manukumar-N/Stouts.postfix
  version: origin/develop
  name: Stouts.postfix

- src: https://github.com/Manukumar-N/ansible-ow-influxdb
  version: origin/master
  name: openwisp.influxdb
